### ISSUE TITLE
Protected Branches: Cannot create a new rule for non-existing branches

### ISSUE THREAD

**Issue by yashwanth-l** [egnyte/gitlabform#103]
using the below in `common_settings.branches` and seeing as below

P.S: Branches with name `release/*` or `release-*` does NOT exists in the `testproject`

`config.yaml` has the below
```yaml
common_settings:
  branches:
    "release/*":
      protected: true
      developers_can_push: false
      developers_can_merge: false
    "release-*":
      protected: true
      developers_can_push: false
      developers_can_merge: false
```

Error:
```
gitlabform.gitlab.core.UnexpectedResponseException: Request url='https://gitlab.com/api/v4/projects/testGroup%2FtestSubGroup%2Ftestproject/repository/branches/release-%2A/protect', method=PUT, data='{'id': 'testGroup/testSubGroup/testproject', 'branch': 'release-*', 'developers_can_push': False, 'developers_can_merge': False}' failed - expected code(s) [200, 201], got code 400 & body: 'b'{"message":"The branch refname is invalid"}''
```
