### ISSUE TITLE
No Capability for Merge Options(Edit Project)

### ISSUE THREAD

**Issue by yashwanth-l** [egnyte/gitlabform#104]
Existing API - `PUT /projects/:id` does have a capability to:
- remove_source_branch_after_merge
- printing_merge_request_link_enabled

These options are under **Merge options** in the UI, but not via `gitlabform`.

Is there a future scope to add these features OR am I missing something?

**Comment by gdubicki** [comment]
Hi @yashwanth-l ! 

Actually this is one of the advantages of GitLabForm - that you can use any parameters that are available in the Projects API without explicit support for them being added to the GitLabForm app, because of [raw parameters passing](https://github.com/egnyte/gitlabform/blob/master/FEATURES_DESIGN.md#raw-parameters-passing).

So please try to add them to your config like this:

```
project_settings:
  "my-group/my-project1":
    project_settings:
      remove_source_branch_after_merge: true
      printing_merge_request_link_enabled: false
```

If it doesn't work then this is a bug.

Please let me know how did it go!
