### ISSUE TITLE
group_secret_variable:  can't change protected/masked value unless key value is changed

### ISSUE THREAD

**Issue by ss7548** [egnyte/gitlabform#107]
```yaml
common_settings:
   group_secret_variables:
      MyVar:
        key: var_name
        value: "some value"
        protected: 1
        masked: 0
        variable_type: env_var
```

1. After the initial run, you cannot update the _protected_ or _masked_ settings unless you change the **value** setting
2.  Contrary to documentation, protected and masked do not honor true/false, you must use 1/0
3. There is no way to delete the variable after you create it, even though there is a delete API.

I am using GitLab omnibus install version 13.0.3-ee
Python 3.8.3
gitlabform 1.15.1

**Comment by gdubicki** [comment]
Hi, thanks for reporting the issue @ss7548 !

1 and 2 look like GitLab limitations, but I will check it out.

3 is a missing feature in GitLabForm. We will consider adding it but frankly we would love to review an external PR with it.

**Comment by ss7548** [comment]
Hi @gdubicki 
Two observations, using curl

- I can update the value for masked and protected without changing the value
- The masked and protected keywords will honor true/false or 1/0

$ curl -X PUT -d protected=true --header "PRIVATE-TOKEN: xyz12345-oop" https://gitlab.somewhere.com/api/v4/groups/80/variables/JAKE
{"variable_type":"env_var","key":"JAKE","value":"ThisISVerySecretPassword","protected":true,"masked":true}

$ curl -X PUT -d protected=false --header "PRIVATE-TOKEN: xyz12345-oop" https://gitlab.somewhere.com/api/v4/groups/80/variables/JAKE
{"variable_type":"env_var","key":"JAKE","value":"ThisISVerySecretPassword","protected":false,"masked":true}

**Comment by ss7548** [comment]
wrt using true/false for masked and protected, you must quote them in the config, i.e.

```yaml
common_settings:
   group_secret_variables:
      MyVar:
        key: var_name
        value: "some value"
        protected: "true"
        masked: "false"
        variable_type: env_var
```
