### ISSUE TITLE
Add Container Registry Expiration policy support

### ISSUE THREAD

**Issue by glensc** [egnyte/gitlabform#114]
- https://docs.gitlab.com/ee/user/packages/container_registry/#expiration-policy

**Comment by glensc** [comment]
a quick search didn't get any results:
- https://github.com/egnyte/gitlabform/search?q=container_registry&unscoped_q=container_registry

so created the issue.

**Comment by gdubicki** [comment]
Thanks! We are open to a PR that would add this feature. :)

**Comment by gdubicki** [comment]
It looks like this feature is already available in GitLabForm as this is configured with the `project_settings`, see https://docs.gitlab.com/ee/user/packages/container_registry/#use-the-cleanup-policy-api .

That example should translate to this config snippet:

```
project_settings:
  foo/bar:
    project_settings:
      container_expiration_policy_attributes:
        cadence: "1month"
        enabled: true
        keep_n: 1
        older_than: "14d"
        name_regex: ""
        name_regex_delete: ".*"
        name_regex_keep: ".*-master"
```

Can you please check if it works, @glensc ?
