### ISSUE TITLE
Hierarchical .gitlab-ci.yml file management

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#12]
(Perhaps it's out of the scope of this app and should be done with some templating tool after #5 is implemented, but I would like to describe the idea here anyway.)

It would be nice to be able to manage `.gitlab-ci.yml` files in an additive way.

For example we have some tests that are shared for all repos in group X, but would like to add some additional ones only in projects X/p1 and X/p2.

Other example is that we do deployments in all repos in group X the same way, except that we don't do them at all for project X/p3.

I am thinking about using a new config section, let's say 'gitlab_ci_yaml' (this name is on purpose different that the filename so that it won't be confused with `files:` entry), that could accept `.gitlab-ci.yml` syntax extended with some templating features, like:

* extra key "gitlabform_skip: true" would make given element not added to the final file,
* extra key "gitlabform_replace: true" would make given element replace with an element of the same name found on a higher level,
* extra key "gitlabform_merge: true" would make given element merge with an element of the same name found on a higher level

I would not use either merging or replacing by default, because the default is non-obvious and expect one of the 2 last keys to be present if you redefine some element, like a job, on a lower 

Example config:

```yaml

group_settings:
  X:
    gitlab_ci_yaml:
      branches: all
      yaml:
        variables:
          THING_A: some_value

        stages:
          - test
          - deploy

        test:
          stage: test
          script:
            - ./run_test.sh

        deployment:
          stage: deploy
          script:
            - ./deploy.sh

project_settings:
  X/p1:
    gitlab_ci_yaml:
      branches: all
      yaml:
        test_something_p1_specific:
          stage: test
          script:
            - ./run_test_p1.sh

       deployment:
         gitlabform_replace: true
         stage: deploy
         script:
          - ./deploy_p1.sh
```

Effective `.gitlab-ci.yml` in all projects in X group except p1:

```yaml
variables:
  THING_A: some_value

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - ./run_test.sh

deployment:
  stage: deploy
  script:
    - ./deploy.sh
```

..and in X/p1:

```yaml
variables:
  THING_A: some_value

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - ./run_test.sh

test_something_p1_specific:
  stage: test
  script:
    - ./run_test_p1.sh

deployment:
  stage: deploy
  script:
    - ./deploy_p1.sh
```

If anyone reads this :P then please let me know what you think about this proposal.
