### ISSUE TITLE
Support multiple config files

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#13]
It may be good to read more than one config file to have more smaller files with configs for different groups rather than one big file with everything.

But to avoid the effective config being hard(er) to understand I would NOT support having config for a single group/project spread in more than one file.

**Comment by weakcamel** [comment]
I quite appreciate how Gitlab people implemented it Gitlab CI:

* [include](https://docs.gitlab.com/ee/ci/yaml/#include)
* [extends](https://docs.gitlab.com/ee/ci/yaml/#extends)

which results in [#using-extends-and-include-together](https://docs.gitlab.com/ee/ci/yaml/#using-extends-and-include-together)

But even with a simple merge of multiple configs could be helpful when paired with Yaml anchors, e.g.

```yaml
---
# group_foo.yaml

'foogroup': &foogroup
    deploy_keys: []
```

```yaml
---
# group_bar.yaml

'bargroup': &bargroup
    deploy_tokens: []
```

```
---
# main config
group_config:
    <<: 
      - *foogroup
      - *bargroup

**Comment by ep-linden** [comment]
I agree with @weakcamel. Definitely would like to have something like that for GitLabForm

**Comment by ep-linden** [comment]
Hi @gdubicki, we created a tool a while ago to output a "merged" YAML file with references to other YAML files using the `extends` keyword like GitLab. We were thinking of integrating the tool we created with GitLabForm, but we first wanted to start a discussion on the design and its potential implementation, or if you even think something like that should be within the scope of GitLabForm.

**Comment by gdubicki** [comment]
Sounds interesting @ep-linden! Can you share a bit more info about how your solution works?

**Comment by ep-linden** [comment]
> Sounds interesting @ep-linden! Can you share a bit more info about how your solution works?

I'll definitely get back to you on this. I think it is best to get the inheritance-break fix out of the way first 😅

**Comment by armingerten** [comment]
I started to structure my configuration using multiple `config_*.yml` files already. If GitLabForm allowed multiple config files via `-c` parameter, I'd be very happy. 😉 

Currently I am using the following workaround instead:

- I split the `config.yml` into multiple files (e.g. `config_foo.yml` and `config_bar.yml`)
- In my case, I run GitLabForm within a (scheduled) pipeline running on my self-hosted GitLab instance
- I use [yq](https://mikefarah.gitbook.io/yq/) to merge all `config_*.yml` files to compile a `config.yml` in a `prepare` stage

The pipeline definition looks like this:

```yaml
stages: [prepare, run]

merge_config:
  stage: prepare
  image: gitlabform/gitlabform:3.0.0
  script:
    - apk update && apk add yq
    - yq ea '. as $item ireduce ({}; . * $item )' config_*.yml > config.yml
  artifacts:
    paths: ["config.yml"]
    expire_in: 7 days

run:
  extends: .run-base
  script: gitlabform -k ALL_DEFINED
```

**Comment by mfriedenhagen** [comment]
👋  @armingerten did you find a solution for reusing YAML anchors with `yq`?

**Comment by armingerten** [comment]
Yes, I also faced that problem when merging multiple files using `yq`. I ended up just sorting the keys on the root level of my YAML file by altering the following expression:

```
yq ea '. as $item ireduce ({}; . * $item )' config_*.yml > config.yml
```
into this:
```
yq ea '. as $item ireduce ({}; . * $item ) | sort_keys(.)' config_*.yml > config.yml
```

This assumes that you are prefixing your "hidden nodes" containing the anchors with e.g. `.` or `__`. Sorting them ahead of non-hidden nodes ensures that they can be referenced within the final config.yml .

**Comment by ep-linden** [comment]
Starting next week I'll be replying as @tdslinden, my personal GitHub. 

Anyway, I have created a tool that takes something like this: 
```
config_version: 3

gitlab:
  url: https://gitlab.example.com/
  token: token

projects_and_groups:
  my-group/*:
    extend: ./instance-group/base-project-settings.yml
```

to this:
```
config_version: 3
gitlab:
  url: https://gitlab.example.com/
  token: token
projects_and_groups:
  my-group/*:
    project_settings:
      description: Update it through [gitlab-configuration project](https://gitlab.example.com/project)
      topics: []
      merge_method: rebase_merge
      resolve_outdated_diff_discussions: false
      remove_source_branch_after_merge: true
      squash_option: default_on
```
