### ISSUE TITLE
Protected tags doesn't accept number 0

### ISSUE THREAD

**Issue by glensc** [egnyte/gitlabform#172]
```yml
    tags:
      "v*":
        protected: true
        create_access_level: 0
```

this is treated as if `create_access_level` wasn't present at all:

![image](https://user-images.githubusercontent.com/199095/106261244-fd6ea480-6229-11eb-8437-f491265dd8f7.png)

A workaround is to quote the value:

```yml
    tags:
      "v*":
        protected: true
        create_access_level: "0"
```
