### ISSUE TITLE
Feature: Support filter parameter for secrets or CI/CD variables

### ISSUE THREAD

**Issue by amimas** [egnyte/gitlabform#186]
Below is an example config I'm trying to use for managing some CI CD variables that are associated with specific "GitLab Environments". In this example, I am using the same name for the variable (i.e. `APP_HOST_AWS_ACCESS_KEY_ID`) but it is scoped to specific environments.

This allows me to have a simpler CI config (i.e. `.gitlab-ci.yml` file) because the appropriate variable will be exposed by GitLab depending on the "environment" that the CI is targeting.

Unfortunately, the following configuration is not working. When it is processed by gitlabform, there is only 1 variable added to the project, which is variable for "staging" environment. I believe that's because they are being processed alphabetically.

```yml
project_settings:
  group-name/project1:
    secret_variables:
      aws_access_key_id_for_deploying_in_production:
        key: APP_HOST_AWS_ACCESS_KEY_ID
        value: "prod-value-1234"
        protected: true
        masked: true
        environment_scope: "production"

      aws_access_key_id_for_deploying_in_staging:
        key: APP_HOST_AWS_ACCESS_KEY_ID
        value: "staging-value-1234"
        protected: true
        masked: true
        environment_scope: "staging"
```

I believe gitlabform is using the following endpoint for creating/updating variables.

https://docs.gitlab.com/ee/api/project_level_variables.html#update-variable

In my case, I think the update needs to happen by filtering `environment_scope`. That way appropriate variable will be updated. I don't think gitlabform currently has logic for this.

https://docs.gitlab.com/ee/api/project_level_variables.html#the-filter-parameter

Would it be possible for adding support for the filter parameter? Or, is there something I missed in my config so that I can set variable with same name but scoped to different environments?

**Comment by gdubicki** [comment]
Hi @amimas !

Frankly the GitLab API docs for that feature are not very clear to me, but perhaps it would be enough to change your config to:

```
 project_settings:
  group-name/project1:
    secret_variables:
      aws_access_key_id_for_deploying_in_production:
        key: APP_HOST_AWS_ACCESS_KEY_ID
        value: "prod-value-1234"
        protected: true
        masked: true
        environment_scope: "production"
        "filter[environment_scope]": "production"

      aws_access_key_id_for_deploying_in_staging:
        key: APP_HOST_AWS_ACCESS_KEY_ID
        value: "staging-value-1234"
        protected: true
        masked: true
        environment_scope: "staging"
        "filter[environment_scope]": "staging"
```

?
