### ISSUE TITLE
merge_requests/approvals is replaced instead of merged

### ISSUE THREAD

**Issue by GianlucaFicarelli** [egnyte/gitlabform#197]
Hi, it seems that nested configurations defined in both `common_settings` and `group_settings` are replaced, instead of merged.

For example, when defining a configuration like this:
```
common_settings:
  merge_requests:
    approvals:
      approvals_before_merge: 3

group_settings:
  "group_name":
    merge_requests:
      approvals:
        merge_requests_author_approval: true
```
and running 
```
gitlabform -v --noop -c config.yaml group_name/project_name
```
The result is
```
GitLabForm version: 1.21.0 (the latest)
Reading config from file: config.yaml
Connected to GitLab version: 13.10.3-ee (db2e358dba4)
Reading config from file: config.yaml
*** # of groups to process: 0
*** # of projects to process: 1
* [1/1] Processing: group_name/project_name
Processing merge_requests in dry-run mode.
Project group_name/project_name approvals changes:
merge_requests_author_approval: "???" => true
```
i.e. only `merge_requests_author_approval` is applied, while I would expect that both the configurations are applied:
- `approvals_before_merge` from `common_settings`
- `merge_requests_author_approval` from `group_settings`

What is the expected behaviour?
Should the `approvals` sections be merged together as I was expecting?
