### ISSUE TITLE
You can't enable builds for private projects

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#2]
Because of GitLab bug https://gitlab.com/gitlab-org/gitlab-ce/issues/27298 you can't use the following config:

```
my_group/my_project:
  project_settings:
    builds_enabled: true
    visibility_level: 0
```

because it results in HTTP 400 response from GitLab API:

```
{
  'project_feature.builds_access_level': [
    'cannot have higher visibility level than repository access level'
  ]
}
```

This is of the long standing bugs that was one of the reasons we implemented project skipping: https://github.com/egnyte/gitlabform/blob/master/config.yml#L119

But we can no longer skip such projects so I plan to implement a better workaround that will allow skipping only a part of project config (such as `project_settings`, `deploy_keys` etc.), even if it is configured on a group level (like we do for files: https://github.com/egnyte/gitlabform/blob/master/config.yml#L117 ).

**Comment by gdubicki** [comment]
So as a workaround for this you should skip project_settings for single projects within a group which have this problem, like this:

```yaml
my_group/my_project:
  project_settings:
    skip: true
```
