### ISSUE TITLE
Using members triggers an email for every gitlabform run

### ISSUE THREAD

**Issue by Pigueiras** [egnyte/gitlabform#200]
In a config like:

```
project_settings:
  project:
    members:
      users:
        pigueiras:
          access_level: 40
```

I get an email like this for every gitlabform run, which is kinda annoying:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/1941284/116715829-5d1a4e80-a9d7-11eb-806d-481bf73fcbfe.png">

I guess this is the problem: https://github.com/egnyte/gitlabform/blob/b1538152cae040a0475779c258ff6071e8a5e175/gitlabform/gitlabform/processors/project/members_processor.py#L43

Maybe we can check if the user is there before removing it?
