### ISSUE TITLE
Deep merge doesn't work as expected (in v2)

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#209]
**Describe the bug**

When trying out a new v2 RC with our production config (>1000 project, >50 groups) I noticed that the effective configuration of some project was in fact combined value of that project and a project before.

In other words for config:

```
projects_and_groups:
  "some_group/*":
    secret_variables:
      first:
        key: foo
        value: bar

  "some_group/my_project":
    secret_variables:
      second:
        key: foo
        value: bar
```

...the effective config when run for whole group `some_group` was:

```
some_group/a_project_before_my_project:
    secret_variables:
      first:
        key: foo
        value: bar
(...)
some_group/my_project:
    secret_variables: # this is correct
      first:
        key: foo
        value: bar
      second:
        key: foo
        value: bar
some_group/some_project_after_my_project:
    secret_variables:
      first:
        key: foo
        value: bar
      second: # this should not be here
        key: foo
        value: bar
some_group/some_other_project_after_my_project:
    secret_variables:
      first:
        key: foo
        value: bar
      second: # this should not be here
        key: foo
        value: bar
(...)
```

When testing the effective config for a single project like `some_group/some_project_after_my_project` the output is correct.

I am pretty sure that it's a bug in deep merge. :( cc @Pigueiras

**GitLabForm version**

```
� GitLabForm version: 2.0.0rc5 = pre-release � (the latest stable is 1.23.0)
```
(Emoji are now shown properly here :( )
