### ISSUE TITLE
Help debug slow processing of gitlabform

### ISSUE THREAD

**Issue by amimas** [egnyte/gitlabform#266]
Hello,

I'm still using gitlabform v1. One issue I have right now is that gitlabform is very slow applying some configs.

I have separated my configs into multiple files. The example config below shows configuring access to all projects under `group1/`. I execute the following config as `gitlabform --config path/to/config/file.yml --skip-archived-projects group1`.

My main issue is that the following config takes almost an hour to complete. The `group1` has about 100 projects. What I can't figure out is why it takes so long. I have a separate config file that I use for managing other settings (i.e. merge request, pipeline, approval, branch protection, etc.) for each projects in the same group. For that config to be applied to all projects in that same group takes only a few minutes.

I'd appreciate if you can give some insight to this.

```yml
gitlab:
  api_version: 4

common_settings:
  # Common settings to set for all groups
  group_settings:
    project_creation_level: maintainer
    subgroup_creation_level: owner
    visibility: internal

  # Common settings to set for all projects
  members:
    groups:
      group-team1:
        group_access: 30  # Developer
      group-team2:
        group_access: 30  # Developer
      group-team3:
        group_access: 30  # Developer
      group-team4:
        group_access: 30  # Developer
      group-team5:
        group_access: 30  # Developer
      group-team6:
        group_access: 30  # Developer
      group-team7:
        group_access: 30  # Developer
      group-team8:
        group_access: 30  # Developer
      group-team9:
        group_access: 40  # Maintainer
      group-team10:
        group_access: 30  # Developer
      group-team11:
        group_access: 30  # Developer

  ## API: https://docs.gitlab.com/ee/api/projects.html#edit-project
  ### GitLab UI: Project -> Settings -> General -> Visibility, project features, permissions

  project_settings:
    visibility: internal
    issues_access_level: enabled
    request_access_enabled: false
    repository_access_level: enabled
    merge_requests_access_level: enabled
    forking_access_level: disabled
    builds_access_level: enabled
    public_builds: true
    lfs_enabled: true
    packages_enabled: false
    show_default_award_emojis: true
    wiki_access_level: disabled
    snippets_access_level: disabled
    analytics_access_level: enabled

# Manage projects with special access controls
project_settings:
  group1/project1:
    project_settings:
      visibility: private
    members:
      groups:
        group-team1:
          group_access: 30  # Developer
        group-team2:
          group_access: 30  # Developer

  group1/project2:
    members:
      groups:
        group-team3:
          group_access: 40  # Maintainer

    deploy_keys:
      deploy-key-name1:
        key: "ssh-ed25519 abcd1234wxyz key-comment"
        title: deploy-key-title
        can_push: true

  group1/project3:
    deploy_keys:
      deploy-key-name1:
        key: "ssh-ed25519 abcd1234wxyz key-comment"
        title: deploy-key-title
        can_push: false

  group1/project4:
    members:
      groups:
        group-team4:
          group_access: 40  # Maintainer

  group1/project5:
    project_settings:
      visibility: private
    members:
      groups:
        group-team5:
          group_access: 40  # Maintainer

  group1/project6:
    project_settings:
      visibility: private
    members:
      groups:
        group-team5:
          group_access: 30  # Developer
        group-team6:
          group_access: 30  # Developer
      users:
        user1:
          access_level: 40  # Maintainer
        user2:
          access_level: 30  # Developer
        user3:
          access_level: 30  # Developer
        user4:
          access_level: 30  # Developer
        user5:
          access_level: 30  # Developer
        user6:
          access_level: 30  # Developer

  group1/project7:
    members:
      groups:
        group-team10:
          group_access: 30  # Developer

group_settings:
  ## Settings of group ##
  commerce-cloud:
    group_settings:
      description: Group description.

skip_groups:
  # Skip processing the following group as it is managed using a separate configuration
  - group1/playground
```
