### ISSUE TITLE
Can't override Code Owner Approval for project

### ISSUE THREAD

**Issue by wokoman** [egnyte/gitlabform#282]
Hi there,

Terribly sorry for treating this as a support, but I can't figure out my problem.

I want to enable a `code_owner_approval_required` rule for a single project, but leave the rest of my group settings intact. However if I do that, I get back:
```shell
failed - expected code(s) [200, 201], got code 403 & body: 'b'{"message":"Feature \'Code Owner Approval Required\' is not enabled"}
```
However, if I remove all of my group rules and only trigger rule set for this specific project, it goes through. Leading me to believe that some settings within the first block is clashing with `code_owner_approval_required` rule. Any idea, what it could be?

I've tried to set `code_owner_approval_required: false` for my _engineering/*_ block, but did not help.

Here's my config:
```yaml
example_config: false

config_version: 2

gitlab:
  api_version: 4
  ssl_verify: true
  timeout: 30

projects_and_groups:
  "engineering/*":
    repository:
      forks_enabled: false

    project_settings:
      jobs_enabled: true
      visibility: internal
      only_allow_merge_if_pipeline_succeeds: true
      wiki_enabled: false

    project_push_rules:
      commit_message_regex: ''
      deny_delete_tag: false
      member_check: false
      prevent_secrets: true
      max_file_size: 0

    branches:
      master:
        protected: true
        push_access_level: 0
        merge_access_level: 30
        unprotect_access_level: 40

    merge_requests:
      approvals:
        approvals_before_merge: 1
        disable_overriding_approvers_per_merge_request: true
        reset_approvals_on_push: false
        merge_requests_author_approval: true
        merge_requests_disable_committers_approval: false
        require_password_to_approve: false
        
  "engineering/some/project":
    project_settings:
      only_allow_merge_if_all_discussions_are_resolved: true

    project_push_rules:
      commit_message_regex: '(\w+-\d+:\s)(.{1,72})(?:\n\n.{1,72})?|Update .+ to v\d+(.\d+)?(.\d+)(.+)?'

    branches:
      master:
        code_owner_approval_required: true

    merge_requests:
      approvals:
        merge_requests_author_approval: false
```
