### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by VasifAghayev** [egnyte/gitlabform#510]
Hi,

I have the following configuration related to protected branches in config.yaml file: 
```
main:
     protected: true
     allowed_to_merge:
        - access_level: developer
     allowed_to_unprotect:
        - access_level: maintainer
     allowed_to_push:
        - user: user_name
```
However, when I checked protected branches via API, I got the following response:
```
 {
    "id": 186414,
    "name": "main",
    "push_access_levels": [
      {
        "access_level": 40,
        "access_level_description": "some-description",
        "user_id": user_id,
        "group_id": null
      }
    ],
    ...
```
Why is the value of "access_level" parameter not null? Is it expected behavior? Maybe I missing something because I thought with the above-mentioned configuration the value of access_level should be null
