### ISSUE TITLE
Working with groups with spaces

### ISSUE THREAD

**Issue by dodwmd** [egnyte/gitlabform#62]
Currently you don't seem to be able to operate against groups with spaces.

**Comment by gdubicki** [comment]
Hi @dodwmd ! I created a group named "test group" in my GitLab instance and in its URL space is replaced with a dash - "test-group" . When I used it in my config:

```

  group_settings: 
    'test-group':
      project_settings: 
        only_allow_merge_if_build_succeeds: true
        only_allow_merge_if_all_discussions_are_resolved: true
```
..it worked as expected:
```
(venv) gdubicki@mac ~/git/gitlabform (master)*$ gitlabform -v -c ../config.yml ALL_DEFINED
Reading config from: ../config.yml
Connected to GitLab version: 12.1.4-ee (4ea82400e72)
Config file is declared to be compatible with GitLab API v4
Reading config from: ../config.yml
>>> Processing ALL groups and projects defined in config
*** # of groups to process: 1
*** # of projects to process: 1
* [1/1] Processing: test-group/test
Setting project_settings
Setting project settings: {'only_allow_merge_if_build_succeeds': True, 'only_allow_merge_if_all_discussions_are_resolved': True}
```
Is this what you needed? If not then please elaborate on what does not work for you.
